import React from 'react'
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer'

// Define styles
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: '1 solid #000',
    paddingBottom: 10,
  },
  companyName: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  companyInfo: {
    fontSize: 9,
    color: '#333',
  },
  section: {
    marginBottom: 15,
    borderBottom: '1 solid #ddd',
    paddingBottom: 10,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  row: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  label: {
    width: '40%',
    fontSize: 9,
    color: '#666',
  },
  value: {
    width: '60%',
    fontSize: 9,
    fontWeight: 'bold',
  },
  table: {
    marginTop: 8,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottom: '2 solid #000',
    paddingBottom: 4,
    marginBottom: 4,
    fontWeight: 'bold',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: '1 solid #eee',
    paddingVertical: 4,
  },
  col1: { width: '40%', fontSize: 9 },
  col2: { width: '15%', fontSize: 9, textAlign: 'right' },
  col3: { width: '15%', fontSize: 9, textAlign: 'right' },
  col4: { width: '15%', fontSize: 9, textAlign: 'right' },
  col5: { width: '15%', fontSize: 9, textAlign: 'right' },
  netPayBox: {
    marginTop: 15,
    padding: 15,
    backgroundColor: '#f0f0f0',
    border: '2 solid #000',
    textAlign: 'center',
  },
  netPayLabel: {
    fontSize: 12,
    marginBottom: 4,
  },
  netPayAmount: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  watermark: {
    position: 'absolute',
    top: 300,
    left: 50,
    right: 50,
    fontSize: 48,
    color: '#ddd',
    opacity: 0.3,
    transform: 'rotate(-45deg)',
    textAlign: 'center',
  },
  ytdSummary: {
    marginTop: 10,
    fontSize: 9,
    color: '#666',
    textAlign: 'center',
  },
})

interface PayStubData {
  company_name: string
  company_address?: string
  company_phone?: string
  company_ein?: string
  employee_name: string
  employee_address?: string
  employee_id_number?: string
  ssn_last_four?: string
  pay_method: string
  pay_period_start: string
  pay_period_end: string
  pay_date: string
  pay_frequency: string
  earnings: Array<{
    description: string
    type: string
    hours?: number
    rate?: number
    amount: number
  }>
  deductions: Array<{
    description: string
    type: string
    amount: number
  }>
  gross_pay: number
  total_deductions: number
  net_pay: number
  ytd_gross: number
  ytd_deductions: number
  ytd_net: number
}

interface PayStubPDFTemplateProps {
  data: PayStubData
  isWatermarked?: boolean
}

export const PayStubPDFTemplate: React.FC<PayStubPDFTemplateProps> = ({
  data,
  isWatermarked = false,
}) => {
  const formatCurrency = (amount: number) => {
    return `$${amount.toLocaleString('en-US', {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`
  }

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: '2-digit',
      day: '2-digit',
      year: 'numeric',
    })
  }

  const getPayMethodDisplay = (method: string) => {
    const methods: Record<string, string> = {
      direct_deposit: 'Direct Deposit',
      check: 'Check',
      cash: 'Cash',
    }
    return methods[method] || method
  }

  const getPayFrequencyDisplay = (frequency: string) => {
    const frequencies: Record<string, string> = {
      weekly: 'Weekly',
      biweekly: 'Bi-Weekly',
      semimonthly: 'Semi-Monthly',
      monthly: 'Monthly',
    }
    return frequencies[frequency] || frequency
  }

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Watermark for free tier */}
        {isWatermarked && (
          <Text style={styles.watermark}>SAMPLE — Generated by ToolSuite</Text>
        )}

        {/* Company Header */}
        <View style={styles.header}>
          <Text style={styles.companyName}>{data.company_name}</Text>
          {data.company_address && (
            <Text style={styles.companyInfo}>{data.company_address}</Text>
          )}
          {data.company_phone && (
            <Text style={styles.companyInfo}>Phone: {data.company_phone}</Text>
          )}
          {data.company_ein && (
            <Text style={styles.companyInfo}>EIN: {data.company_ein}</Text>
          )}
        </View>

        {/* Employee & Pay Period Info */}
        <View style={styles.section}>
          <View style={{ flexDirection: 'row' }}>
            {/* Left column - Employee */}
            <View style={{ width: '50%' }}>
              <Text style={styles.sectionTitle}>Employee</Text>
              <View style={styles.row}>
                <Text style={styles.label}>Name:</Text>
                <Text style={styles.value}>{data.employee_name}</Text>
              </View>
              {data.employee_address && (
                <View style={styles.row}>
                  <Text style={styles.label}>Address:</Text>
                  <Text style={styles.value}>{data.employee_address}</Text>
                </View>
              )}
              {data.employee_id_number && (
                <View style={styles.row}>
                  <Text style={styles.label}>Employee ID:</Text>
                  <Text style={styles.value}>{data.employee_id_number}</Text>
                </View>
              )}
              {data.ssn_last_four && (
                <View style={styles.row}>
                  <Text style={styles.label}>SSN:</Text>
                  <Text style={styles.value}>***-**-{data.ssn_last_four}</Text>
                </View>
              )}
              <View style={styles.row}>
                <Text style={styles.label}>Pay Method:</Text>
                <Text style={styles.value}>{getPayMethodDisplay(data.pay_method)}</Text>
              </View>
            </View>

            {/* Right column - Pay Period */}
            <View style={{ width: '50%' }}>
              <Text style={styles.sectionTitle}>Pay Period</Text>
              <View style={styles.row}>
                <Text style={styles.label}>Period:</Text>
                <Text style={styles.value}>
                  {formatDate(data.pay_period_start)} - {formatDate(data.pay_period_end)}
                </Text>
              </View>
              <View style={styles.row}>
                <Text style={styles.label}>Pay Date:</Text>
                <Text style={styles.value}>{formatDate(data.pay_date)}</Text>
              </View>
              <View style={styles.row}>
                <Text style={styles.label}>Frequency:</Text>
                <Text style={styles.value}>{getPayFrequencyDisplay(data.pay_frequency)}</Text>
              </View>
            </View>
          </View>
        </View>

        {/* Earnings */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Earnings</Text>
          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={styles.col1}>Description</Text>
              <Text style={styles.col2}>Hours</Text>
              <Text style={styles.col3}>Rate</Text>
              <Text style={styles.col4}>Current</Text>
              <Text style={styles.col5}>YTD</Text>
            </View>
            {data.earnings.map((earning, index) => (
              <View key={index} style={styles.tableRow}>
                <Text style={styles.col1}>{earning.description}</Text>
                <Text style={styles.col2}>{earning.hours || '—'}</Text>
                <Text style={styles.col3}>{earning.rate ? formatCurrency(earning.rate) : '—'}</Text>
                <Text style={styles.col4}>{formatCurrency(earning.amount)}</Text>
                <Text style={styles.col5}>—</Text>
              </View>
            ))}
            <View style={{ ...styles.tableRow, borderTop: '2 solid #000', fontWeight: 'bold' }}>
              <Text style={styles.col1}>GROSS PAY</Text>
              <Text style={styles.col2}></Text>
              <Text style={styles.col3}></Text>
              <Text style={styles.col4}>{formatCurrency(data.gross_pay)}</Text>
              <Text style={styles.col5}>{formatCurrency(data.ytd_gross)}</Text>
            </View>
          </View>
        </View>

        {/* Deductions */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Deductions</Text>
          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={{ ...styles.col1, width: '60%' }}>Description</Text>
              <Text style={{ ...styles.col4, width: '20%' }}>Current</Text>
              <Text style={{ ...styles.col5, width: '20%' }}>YTD</Text>
            </View>
            {data.deductions.map((deduction, index) => (
              <View key={index} style={styles.tableRow}>
                <Text style={{ ...styles.col1, width: '60%' }}>{deduction.description}</Text>
                <Text style={{ ...styles.col4, width: '20%' }}>{formatCurrency(deduction.amount)}</Text>
                <Text style={{ ...styles.col5, width: '20%' }}>—</Text>
              </View>
            ))}
            <View style={{ ...styles.tableRow, borderTop: '2 solid #000', fontWeight: 'bold' }}>
              <Text style={{ ...styles.col1, width: '60%' }}>TOTAL DEDUCTIONS</Text>
              <Text style={{ ...styles.col4, width: '20%' }}>{formatCurrency(data.total_deductions)}</Text>
              <Text style={{ ...styles.col5, width: '20%' }}>{formatCurrency(data.ytd_deductions)}</Text>
            </View>
          </View>
        </View>

        {/* Net Pay */}
        <View style={styles.netPayBox}>
          <Text style={styles.netPayLabel}>NET PAY</Text>
          <Text style={styles.netPayAmount}>{formatCurrency(data.net_pay)}</Text>
        </View>

        {/* YTD Summary */}
        <Text style={styles.ytdSummary}>
          YTD Summary: Gross {formatCurrency(data.ytd_gross)} | Deductions{' '}
          {formatCurrency(data.ytd_deductions)} | Net {formatCurrency(data.ytd_net)}
        </Text>
      </Page>
    </Document>
  )
}
